### ISSUE TITLE
Bug: 个人介绍以及其他栏位的字数限制与观感不符

### ISSUE THREAD

**Issue by SiBorea** [masquevil/trpg-saikou#5]
个人介绍在最大字数348字，常规尺寸下，不溢出的最大字数是333字，溢出后显示效果如图1。
自适应尺寸的情况下（如手机打开），满字数的个人介绍后面还有大量空行，效果参考图2。

实际车卡时小作文写300字太少了，建议放宽到约800字。打印人物卡时用的是常规尺寸。其他栏位不需要那么多空间和字数

<img width="984" alt="image" src="https://github.com/masquevil/trpg-saikou/assets/108953913/4ce30429-79be-4d3b-8e45-b4d0aeb0584f">
<img width="981" alt="image" src="https://github.com/masquevil/trpg-saikou/assets/108953913/6c96cefc-116e-43c3-84f8-12261c88be59">

**Comment by masquevil** [comment]
https://github.com/masquevil/trpg-saikou/commit/e4900f71d37885bc5a23808b9fbc601d3ed13fba 改到700字了
