### ISSUE TITLE
Bug: 个人介绍的行数多了之后，行间距会出现异常

### ISSUE THREAD

**Issue by SiBorea** [masquevil/trpg-saikou#6]
如图

<img width="462" alt="image" src="https://github.com/masquevil/trpg-saikou/assets/108953913/df92ab86-aad7-4c5d-a16e-10ce229708ca">

**Comment by masquevil** [comment]
我复现不出来，什么系统和浏览器？

**Comment by SiBorea** [comment]
Mac Safari以及iOS Safari/微信。全部最新版系统和浏览器

![image](https://github.com/masquevil/trpg-saikou/assets/108953913/67918784-ab8a-4a91-b216-a1a9c89d29e4)
![image](https://github.com/masquevil/trpg-saikou/assets/108953913/2e19b9a4-2aa2-4ef7-97c4-39af4ec15547)

**Comment by masquevil** [comment]
修好了
