### ISSUE TITLE
Bug: 导出之后排版有误

### ISSUE THREAD

**Issue by SiBorea** [masquevil/trpg-saikou#7]
如图

<img width="770" alt="image" src="https://github.com/masquevil/trpg-saikou/assets/108953913/47e076be-b8a1-4804-9391-7452d987afb4">

**Comment by masquevil** [comment]
还是复现不了，什么环境？

**Comment by SiBorea** [comment]
不清楚。KP发出来其他PL的人物卡，pdf格式。我自己的没问题。

**Comment by masquevil** [comment]
pdf 的话，目前肯定是 pc/mac 使用打印保存为 pdf 出来的，但我 windows 和 mac 都没试出来。先不管了，后面有人报具体信息再说吧
